### ISSUE TITLE
Problem with the Usage commend.

### ISSUE THREAD

**Issue by showcy** [UBC-MDS/inference_on_indigenous_vs_non_indigenous_sentence_length_differences#12]
I am not sure if it is different to use this command on Mac or Windows, but the command you write there does now work for me.
`python src/download_data.py --url="http://www.csc-scc.gc.ca/005/opendata-donneesouvertes/Open%20Data%20File%2020170409%20v3%20(English).csv" --file_path="../data/raw/offender_profile.csv".csv" --file_path="./data/raw/offender_profile.csv"
`
It seems you have two `file_path` argument?

I modified the command as the following and it works for me:
`python src/download_data.py --url="http://www.csc-scc.gc.ca/005/opendata-donneesouvertes/Open%20Data%20File%2020170409%20v3%20(English).csv" --file_path="data/raw/offender_profile.csv"`

Any idea?

**Comment by showcy** [comment]
One more problem, we need to change the `sample-docopt.r` to `clean_offender_profile_raw_data.r` for this command:
`Rscript src/sample-docopt.r --raw_data_path="./data/raw/offender_profile.csv" --processed_dir_path="./data/processed"`

**Comment by miyer26** [comment]
Agreed, changes have been incorporated.

**Comment by showcy** [comment]
Solved.
