### ISSUE TITLE
Problem with clean_offender_profile_raw_data.r

### ISSUE THREAD

**Issue by showcy** [UBC-MDS/inference_on_indigenous_vs_non_indigenous_sentence_length_differences#13]
I got error when running the command directly. And then I checked the source code and realized it seems you missed `skip = 1` for `read_csv` on line 19. Please check.

**Comment by AraiYuno** [comment]
I saw your changes. Did you run @Radascript's code to make sure nothing has been broken?

**Comment by miyer26** [comment]
Ran into an issue without using the solution provided above, changes have been incorporated to the script

**Comment by showcy** [comment]
Solved.
