### ISSUE TITLE
What should be the name of our repo / project?

### ISSUE THREAD

**Issue by AraiYuno** [UBC-MDS/inference_on_indigenous_vs_non_indigenous_sentence_length_differences#4]
Based on our previous meeting, we decided to conduct hypothesis testing to see whether there is a statistically significant difference between the length of sentences of indigenous non-indigenous people.

Pleaes share your ideas for the name of the repo!

**Comment by Radascript** [comment]
Statistical significance of indigenous vs non-indigenous racial grouping as a factor in determining aggregated sentence length in Canada?

**Comment by miyer26** [comment]
Inference on sentence length based on racial groups?

**Comment by AraiYuno** [comment]
Project Name: "Do indigenous people get different sentence lengths than non-indigenous people?"
Repo Name: "inference_on_indigenous_vs_non_indigenous_sentence_length_differences"
Asking an interesting question sometimes attracts people to read in our analysis haha.

**Comment by AraiYuno** [comment]
Final project name: Statistical significance of indigenous vs non-indigenous racial grouping as a factor in determining aggregated sentence length in Canada?

Repo name: inference_on_indigenous_vs_non_indigenous_sentence_length_differences
